spring:
  security:
    user:
      name: admin
      password: admin
      roles: USER

  jms:
    listener:
      acknowledge-mode: client
      auto-startup: true
      concurrency: 1
      max-concurrency: 1
    cache:
      enabled: false

sync:
  title: Jira2Rtc Test
  debug: true
  settingsLocation: settings.json
  appStateLocation: ${user.home}/
  logfile: ${user.home}/issue-sync.log
  pollingCron: 0 0 23 * * ?
  notificationChannelProperties:
    - classname: ch.loewenfels.issuetrackingsync.notification.CsvProtocol
      endpoint: ${user.home}/protocol.csv
