spring:
  security:
    user:
      name: admin
      password: admin
      roles: USER

  jms:
    listener:
      acknowledge-mode: client
      auto-startup: true
      concurrency: 1
      max-concurrency: 1
    cache:
      enabled: false

  activemq:
    packages:
      trusted: ch.loewenfels.issuetrackingsync.scheduling, java.time, java.lang

sync:
  settingsLocation: build/resources/test/settings.json
  pollingCron: 0 0 0 1 * ?
  notificationChannelProperties:
    - classname: ch.loewenfels.issuetrackingsync.notification.SlackChannel
      endpoint: http://localhost:8033
      username: jira2rtc
      subject: hello
      avatar: ":twice:"
