spring:
  security:
    user:
      name: admin
      password: admin
      roles: USER

  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 1
      max-concurrency: 1
    cache:
      enabled: false

  activemq:
    packages:
      trusted: ch.loewenfels.issuetrackingsync.dto, java.time, java.lang

sync:
  settingsLocation: build/resources/test/settings.json
  pollingCron: 0 0 0 1 * ?
