spring:
  security:
    user:
      name: admin
      password: admin

  activemq:
    packages:
      trusted: ch.loewenfels.issuetrackingsync.dto, java.time, java.lang

sync:
  settingsLocation: build/resources/test/settings.json
  pollingCron: 0 0 0 1 * ?
